from .....Qtive.Component import (
    Frame,
    ToolButton,
    Label,
    Stacked,
    TableView,
    Spacer,
    Slider,
    Popup,
    LineEdit,
)
from .....Qtive.Props import (
    height,
    width,
    alignment,
    orientation,
    text,
    attributes,
    source,
    items,
    on_click,
    image,
    aspect_ratio,
    on_update,
    index,
    on_execution,
    deploy,
    on_text_change,
    on_enter_press,
    on_close,
    id,
    spacing,
    margins,
    placeholder,
)
from ....components import Projector, Secondary
from ..viewmodel import MainViewModel


def Onlive():
    vm = MainViewModel()
    oc = vm.oc
    return Frame(
        width("35%"),
        id("box"),
        spacing(5),
        margins(5, 5, 5, 5),
        Frame(
            height("5%"),
            orientation("row"),
            spacing(5),
            ToolButton(
                alignment("left"),
                text("Anunciar"),
                on_click(oc.alert.deploy.emit),
                Popup(
                    height("100%"),
                    width("500%"),
                    spacing(5),
                    margins(5, 5, 5, 5),
                    deploy(oc.alert.deploy),
                    attributes({"direction": "right"}),
                    orientation("row"),
                    LineEdit(
                        width("90%"),
                        text(oc.alert.text),
                        on_text_change(oc.set_alert_text),
                        on_enter_press(oc.emit_announce),
                        placeholder("Escriba aqui su anuncio"),
                    ),
                    ToolButton(text("Ok"), on_click(lambda: oc.emit_announce(""))),
                ),
            ),
            Spacer("horizontal"),
            ToolButton(
                alignment("right"),
                text("Fondo"),
                on_click(oc.change_only_bg),
                attributes(oc.btns.bg_attrs),
            ),
            ToolButton(
                alignment("right"),
                text("Negro"),
                on_click(oc.change_black),
                attributes(oc.btns.black_attrs),
            ),
            ToolButton(
                alignment("right"),
                text("Mostrar"),
                on_click(oc.altern_secondary),
                attributes(oc.btns.secondary_attrs),
            ),
        ),
        Label(height("5%"), text(oc.view.title)),
        Stacked(
            height("46%"),
            index(oc.view.mode),
            TableView(
                items(oc.view.lyrics),
                attributes({"stretch": [1], "selection_mode": "row", "wrap": True}),
                on_click(oc.change_text),
                index(oc.view.focus),
            ),
            Frame(
                Spacer("vertical"),
                margins(5, 5, 5, 5),
                Label(
                    height("10%"),
                    text(oc.player.time),
                    attributes({"text_align": "right"}),
                ),
                Slider(
                    orientation("row"),
                    height("15%"),
                    attributes(oc.player.range),
                    index(oc.player.value),
                    on_update(lambda p: oc.set_attr_player("pos", p)),
                ),
                Frame(
                    orientation("row"),
                    height("15%"),
                    spacing(5),
                    ToolButton(
                        image(oc.btns.play),
                        height("100%"),
                        aspect_ratio("3-2"),
                        on_click(oc.change_play),
                    ),
                    ToolButton(
                        image("stop.svg"),
                        height("80%"),
                        aspect_ratio("3-2"),
                        on_click(oc.set_stop),
                    ),
                    Spacer(),
                    ToolButton(
                        image(oc.btns.mute),
                        height("80%"),
                        aspect_ratio("3-2"),
                        on_click(oc.change_mute),
                    ),
                    Slider(
                        height("100%"),
                        width("20%"),
                        orientation("row"),
                        on_update(lambda v: oc.set_attr_player("volumen", v)),
                        index(oc.player.volumen),
                        attributes({"range": (0, 100)}),
                    ),
                ),
                Spacer("vertical"),
                Frame(height("11%")),
            ),
        ),
        Frame(
            height("44%"),
            id("projector_frame"),
            Projector(
                height("90%"),
                width("90%"),
                alignment("center"),
                source(oc.projector.bg),
                attributes(oc.projector.attrs),
                text(oc.projector.text),
                on_update(lambda t: oc.set_attr_player("time", t)),
                on_execution(lambda d: oc.set_attr_player("duration", d)),
                index(oc.projector.pos),
            ),
        ),
        Secondary(
            deploy(oc.view.secondary),
            on_close(oc.set_secondary),
            Projector(
                id("secondary"),
                source(oc.projector.bg),
                attributes(oc.projector.s_attrs),
                text(oc.projector.text),
                index(oc.projector.pos),
            ),
        ),
    )
